# Generated by Django 4.2.7 on 2023-12-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='website',
        ),
        migrations.RemoveField(
            model_name='data',
            name='website',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.RemoveField(
            model_name='website',
            name='category',
        ),
        migrations.RemoveField(
            model_name='website',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
