# Generated by Django 4.2.7 on 2023-12-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='api_key',
            field=models.CharField(auto_created=True, default='ZLFdHXIUe-ekwJCu', max_length=17, unique=True),
        ),
    ]
