# Generated by Django 4.2.7 on 2023-12-03 07:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_website_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='api_key',
            field=models.CharField(default=app.models.generate_key, max_length=17, unique=True),
        ),
    ]
